<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('distritos')->insert([
            // San Salvador Centro
            [
                'nombre_distrito' => 'San Salvador Centro',
                'codigo_municipio' => '23',
                'nombre_municipio_oficial' => 'San Salvador Centro',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // San Salvador Norte
            [
                'nombre_distrito' => 'San Salvador',
                'codigo_municipio' => '20',
                'nombre_municipio_oficial' => 'San Salvador Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Aguilares',
                'codigo_municipio' => '20',
                'nombre_municipio_oficial' => 'San Salvador Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'El Paisnal',
                'codigo_municipio' => '20',
                'nombre_municipio_oficial' => 'San Salvador Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Guazapa',
                'codigo_municipio' => '20',
                'nombre_municipio_oficial' => 'San Salvador Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // San Salvador Oeste
            [
                'nombre_distrito' => 'San Salvador Oeste',
                'codigo_municipio' => '21',
                'nombre_municipio_oficial' => 'San Salvador Oeste',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Apopa',
                'codigo_municipio' => '21',
                'nombre_municipio_oficial' => 'San Salvador Oeste',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Nejapa',
                'codigo_municipio' => '21',
                'nombre_municipio_oficial' => 'San Salvador Oeste',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // San Salvador Este
            [
                'nombre_distrito' => 'San Salvador Este',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Cuscatancingo',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Delgado',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Ilopango',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Martín',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Soyapango',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Tonacatepeque',
                'codigo_municipio' => '22',
                'nombre_municipio_oficial' => 'San Salvador Este',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // San Salvador Sur
            [
                'nombre_distrito' => 'San Salvador Sur',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Ayutuxtepeque',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Mejicanos',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Panchimalco',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Rosario de Mora',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Marcos',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Santiago Texacuangos',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Santo Tomás',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'San Salvador Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Santa Ana Centro
            [
                'nombre_distrito' => 'Santa Ana',
                'codigo_municipio' => '15',
                'nombre_municipio_oficial' => 'Santa Ana Centro',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Santa Ana Norte
            [
                'nombre_distrito' => 'Masahuat',
                'codigo_municipio' => '15',
                'nombre_municipio_oficial' => 'Santa Ana Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Metapán',
                'codigo_municipio' => '15',
                'nombre_municipio_oficial' => 'Santa Ana Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Santa Rosa Guachipilín',
                'codigo_municipio' => '15',
                'nombre_municipio_oficial' => 'Santa Ana Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Texistepeque',
                'codigo_municipio' => '15',
                'nombre_municipio_oficial' => 'Santa Ana Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Santa Ana Este
            [
                'nombre_distrito' => 'Coatepeque',
                'codigo_municipio' => '16',
                'nombre_municipio_oficial' => 'Santa Ana Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'El Congo',
                'codigo_municipio' => '16',
                'nombre_municipio_oficial' => 'Santa Ana Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Santa Ana Oeste
            [
                'nombre_distrito' => 'Candelaria de la Frontera',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Chalchuapa',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'El Porvenir',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Antonio Pajonal',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Sebastián Salitrillo',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Santiago de la Frontera',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Santa Ana Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Norte
            [
                'nombre_distrito' => 'Quezaltepeque',
                'codigo_municipio' => '23',
                'nombre_municipio_oficial' => 'La Libertad Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Matías',
                'codigo_municipio' => '23',
                'nombre_municipio_oficial' => 'La Libertad Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Pablo Tacachico',
                'codigo_municipio' => '23',
                'nombre_municipio_oficial' => 'La Libertad Norte',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Centro
            [
                'nombre_distrito' => 'Ciudad Arce',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'La Libertad Centro',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Juan Opico',
                'codigo_municipio' => '24',
                'nombre_municipio_oficial' => 'La Libertad Centro',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Oeste
            [
                'nombre_distrito' => 'Colón',
                'codigo_municipio' => '25',
                'nombre_municipio_oficial' => 'La Libertad Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Jayaque',
                'codigo_municipio' => '25',
                'nombre_municipio_oficial' => 'La Libertad Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Sacacoyo',
                'codigo_municipio' => '25',
                'nombre_municipio_oficial' => 'La Libertad Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Talnique',
                'codigo_municipio' => '25',
                'nombre_municipio_oficial' => 'La Libertad Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Tepecoyo',
                'codigo_municipio' => '25',
                'nombre_municipio_oficial' => 'La Libertad Oeste',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Este
            [
                'nombre_distrito' => 'Antiguo Cuscatlán',
                'codigo_municipio' => '26',
                'nombre_municipio_oficial' => 'La Libertad Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Huizúcar',
                'codigo_municipio' => '26',
                'nombre_municipio_oficial' => 'La Libertad Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Nuevo Cuscatlán',
                'codigo_municipio' => '26',
                'nombre_municipio_oficial' => 'La Libertad Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San José Villanueva',
                'codigo_municipio' => '26',
                'nombre_municipio_oficial' => 'La Libertad Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Zaragoza',
                'codigo_municipio' => '26',
                'nombre_municipio_oficial' => 'La Libertad Este',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Sur
            [
                'nombre_distrito' => 'Comasagua',
                'codigo_municipio' => '28',
                'nombre_municipio_oficial' => 'La Libertad Sur',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Libertad Costa
            [
                'nombre_distrito' => 'Chiltiupán',
                'codigo_municipio' => '27',
                'nombre_municipio_oficial' => 'La Libertad Costa',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Jicalapa',
                'codigo_municipio' => '27',
                'nombre_municipio_oficial' => 'La Libertad Costa',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'La Libertad',
                'codigo_municipio' => '27',
                'nombre_municipio_oficial' => 'La Libertad Costa',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Tamanique',
                'codigo_municipio' => '27',
                'nombre_municipio_oficial' => 'La Libertad Costa',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Teotepeque',
                'codigo_municipio' => '27',
                'nombre_municipio_oficial' => 'La Libertad Costa',
                'departamento_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Cuscatlán Norte
            [
                'nombre_distrito' => 'Oratorio de Concepción',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Cuscatlán Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Bartolomé Perulapía',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Cuscatlán Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San José Guayabal',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Cuscatlán Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Pedro Perulapán',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Cuscatlán Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Suchitoto',
                'codigo_municipio' => '17',
                'nombre_municipio_oficial' => 'Cuscatlán Norte',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Cuscatlán Sur
            [
                'nombre_distrito' => 'Candelaria',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Cojutepeque',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'El Carmen',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'El Rosario',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Monte San Juan',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Cristóbal',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Rafael Cedros',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'San Ramón',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //CUSCATLAN
            [
                'nombre_distrito' => 'Santa Cruz Analquito',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Santa Cruz Michapa',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_distrito' => 'Tenancingo',
                'codigo_municipio' => '18',
                'nombre_municipio_oficial' => 'Cuscatlán Sur',
                'departamento_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // La Paz Oeste
            ['nombre_distrito' => 'Cuyultitán', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Olocuilta', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Francisco Chinameca', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Juan Talpa', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Luis Talpa', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Pedro Masahuat', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Tapalhuaca', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'La Paz Oeste', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            // La Paz Centro
            ['nombre_distrito' => 'El Rosario', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Jerusalén', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Mercedes La Ceiba', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Paraíso de Osorio', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Antonio Masahuat', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Emigdio', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Juan Tepezontes', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Luis La Herradura', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Miguel Tepezontes', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Pedro Nonualco', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Santa María Ostuma', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Santiago Nonualco', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'La Paz Centro', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            // La Paz Este
            ['nombre_distrito' => 'San Juan Nonualco', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'La Paz Este', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Rafael Obrajuelo', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'La Paz Este', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Zacatecoluca', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'La Paz Este', 'departamento_id' => 8, 'created_at' => now(), 'updated_at' => now()],

            // Ahuachapán Centro
            ['nombre_distrito' => 'Ahuachapán', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Atiquizaya', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            // Ahuachapán Norte
            ['nombre_distrito' => 'Apaneca', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Concepción de Ataco', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'El Refugio', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Tacuba', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            // Ahuachapán Sur
            ['nombre_distrito' => 'San Pedro Puxtla', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Guaymango', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Jujutla', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Francisco Menéndez', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Turín', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'Ahuachapán Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],

             // Sonsonate Norte
             ['nombre_distrito' => 'Juayúa', 'codigo_municipio' => '17', 'nombre_municipio_oficial' => 'Sonsonate Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Nahuizalco', 'codigo_municipio' => '17', 'nombre_municipio_oficial' => 'Sonsonate Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Salcoatitán', 'codigo_municipio' => '17', 'nombre_municipio_oficial' => 'Sonsonate Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Santa Catarina Masahuat', 'codigo_municipio' => '17', 'nombre_municipio_oficial' => 'Sonsonate Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             // Sonsonate Centro
             ['nombre_distrito' => 'Nahulingo', 'codigo_municipio' => '18', 'nombre_municipio_oficial' => 'Sonsonate Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Antonio del Monte', 'codigo_municipio' => '18', 'nombre_municipio_oficial' => 'Sonsonate Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Sonsonate', 'codigo_municipio' => '18', 'nombre_municipio_oficial' => 'Sonsonate Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Santo Domingo de Guzmán', 'codigo_municipio' => '18', 'nombre_municipio_oficial' => 'Sonsonate Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Sonzacate', 'codigo_municipio' => '18', 'nombre_municipio_oficial' => 'Sonsonate Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             // Sonsonate Este
             ['nombre_distrito' => 'Armenia', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Caluco', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Cuisnahuat', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Izalco', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Julián', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Santa Isabel Ishuatán', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'Sonsonate Este', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
             // Sonsonate Oeste
             ['nombre_distrito' => 'Acajutla', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'Sonsonate Oeste', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],

             // Chalatenango Norte
            ['nombre_distrito' => 'La Palma', 'codigo_municipio' => '34', 'nombre_municipio_oficial' => 'Chalatenango Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Citalá', 'codigo_municipio' => '34', 'nombre_municipio_oficial' => 'Chalatenango Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Ignacio', 'codigo_municipio' => '34', 'nombre_municipio_oficial' => 'Chalatenango Norte', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],

            // Chalatenango Centro
            ['nombre_distrito' => 'La Reina', 'codigo_municipio' => '35', 'nombre_municipio_oficial' => 'Chalatenango Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Nueva Concepción', 'codigo_municipio' => '35', 'nombre_municipio_oficial' => 'Chalatenango Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Tejutla', 'codigo_municipio' => '35', 'nombre_municipio_oficial' => 'Chalatenango Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Agua Caliente', 'codigo_municipio' => '35', 'nombre_municipio_oficial' => 'Chalatenango Centro', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],

            // Chalatenango Sur (solo unos para ejemplo)
            ['nombre_distrito' => 'Chalatenango', 'codigo_municipio' => '36', 'nombre_municipio_oficial' => 'Chalatenango Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Dulce Nombre de María', 'codigo_municipio' => '36', 'nombre_municipio_oficial' => 'Chalatenango Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Nueva Trinidad', 'codigo_municipio' => '36', 'nombre_municipio_oficial' => 'Chalatenango Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Antonio de la Cruz', 'codigo_municipio' => '36', 'nombre_municipio_oficial' => 'Chalatenango Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Santa Rita', 'codigo_municipio' => '36', 'nombre_municipio_oficial' => 'Chalatenango Sur', 'departamento_id' => 6, 'created_at' => now(), 'updated_at' => now()],

             // San Vicente Norte
             ['nombre_distrito' => 'Apastepeque', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Esteban Catarina', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Ildefonso', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Lorenzo', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Sebastián', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Santa Clara', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Santo Domingo', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             // San Vicente Sur
             ['nombre_distrito' => 'Guadalupe', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Cayetano Istepeque', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Vicente', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Tecoluca', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Tepetitán', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Verapaz', 'codigo_municipio' => '15', 'nombre_municipio_oficial' => 'San Vicente Sur', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

              // Cabañas Este
            ['nombre_distrito' => 'Cinquera', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Dolores', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Guacotecti', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Ilobasco', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

            // Cabañas Oeste
            ['nombre_distrito' => 'Jutiapa', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Isidro', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Sensuntepeque', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Tejutepeque', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Victoria', 'codigo_municipio' => '12', 'nombre_municipio_oficial' => 'Cabañas Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

                // Usulután Norte
                ['nombre_distrito' => 'Alegría', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Berlín', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'El Triunfo', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Estanzuelas', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Jucuapa', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Mercedes Umaña', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Nueva Granada', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'San Buenaventura', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Santiago de María', 'codigo_municipio' => '24', 'nombre_municipio_oficial' => 'Usulután Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

                // Usulután Este
                ['nombre_distrito' => 'California', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Concepción Batres', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Ereguayquín', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Jucuarán', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Ozatlán', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'San Dionisio', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Santa Elena', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Santa María', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Tecapán', 'codigo_municipio' => '25', 'nombre_municipio_oficial' => 'Usulután Este', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

                // Usulután Oeste
                ['nombre_distrito' => 'Usulután', 'codigo_municipio' => '26', 'nombre_municipio_oficial' => 'Usulután Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Jiquilisco', 'codigo_municipio' => '26', 'nombre_municipio_oficial' => 'Usulután Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'Puerto El Triunfo', 'codigo_municipio' => '26', 'nombre_municipio_oficial' => 'Usulután Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'San Francisco Javier', 'codigo_municipio' => '26', 'nombre_municipio_oficial' => 'Usulután Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
                ['nombre_distrito' => 'San Agustín', 'codigo_municipio' => '26', 'nombre_municipio_oficial' => 'Usulután Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

                  // San Miguel Norte
            ['nombre_distrito' => 'Carolina', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Chapeltique', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Comacarán', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Moncagua', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Quelepa', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Gerardo', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Uluazapa', 'codigo_municipio' => '21', 'nombre_municipio_oficial' => 'San Miguel Norte', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

            // San Miguel Centro
            ['nombre_distrito' => 'San Miguel', 'codigo_municipio' => '22', 'nombre_municipio_oficial' => 'San Miguel Centro', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Jorge', 'codigo_municipio' => '22', 'nombre_municipio_oficial' => 'San Miguel Centro', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

            // San Miguel Oeste
            ['nombre_distrito' => 'Chinameca', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Chirilagua', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'El Tránsito', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Lolotique', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Nueva Guadalupe', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Antonio', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Luis de la Reina', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Sesori', 'codigo_municipio' => '23', 'nombre_municipio_oficial' => 'San Miguel Oeste', 'departamento_id' => 12, 'created_at' => now(), 'updated_at' => now()],

             // Morazán Norte
             ['nombre_distrito' => 'Arambala', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Cacaopera', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Corinto', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'El Rosario', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Joateca', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Jocoaitique', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Meanguera', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Perquín', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Fernando', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Isidro', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Torola', 'codigo_municipio' => '27', 'nombre_municipio_oficial' => 'Morazán Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],

             // Morazán Sur
             ['nombre_distrito' => 'Chilanga', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Delicias de Concepción', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'El Divisadero', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Gualococti', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Guatajiagua', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Jocoro', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Lolotiquillo', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Osicala', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Carlos', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Francisco Gotera', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'San Simón', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Sensembra', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Sociedad', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Yamabal', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
             ['nombre_distrito' => 'Yoloaiquín', 'codigo_municipio' => '28', 'nombre_municipio_oficial' => 'Morazán Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],

               // La Unión Norte
            ['nombre_distrito' => 'Anamorós', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Bolívar', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Concepción de Oriente', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'El Sauce', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Lislique', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Nueva Esparta', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Pasaquina', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Polorós', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San José', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Santa Rosa de Lima', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Yayantique', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Yucuaiquín', 'codigo_municipio' => '19', 'nombre_municipio_oficial' => 'La Unión Norte', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],

            // La Unión Sur
            ['nombre_distrito' => 'La Unión', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Conchagua', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'El Carmen', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Intipucá', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'Meanguera del Golfo', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['nombre_distrito' => 'San Alejo', 'codigo_municipio' => '20', 'nombre_municipio_oficial' => 'La Unión Sur', 'departamento_id' => 15, 'created_at' => now(), 'updated_at' => now()],
        ]);

    }
}
